improve passgen

diff --git a/bin/passgen b/bin/passgen
--- a/bin/passgen
+++ b/bin/passgen
@@ -1,5 +1,9 @@
 #!/usr/bin/env bash
 
+# This script generates a password using the provided dictionary
+# with some numbers and special characters sprinkled on top.
+# The dictionary should be in the same directory as the script.
+
 DICT_DIR="$(dirname "$(readlink -f "$0")")"
 
 wordnum=4
@@ -7,7 +11,25 @@ wordnum=4
 specialchars="!@#$%^&*?;:~"
 chrlen=$((${#specialchars} - 1))
 
-words=( $(shuf --random-source=/dev/urandom -r -n "$wordnum" < $DICT_DIR/passgen.dic) )
+dict="${DICT_DIR}/passgen.dic"
+
+if [ ! -f "$dict" ]; then
+    echo "ERROR: missing dictionary." 1>&2
+    exit 1
+fi
+
+if ! command -v "shuf" >/dev/null 2>&1
+then
+    echo "ERROR: GNU shuf could not be found."
+    exit 1
+fi
+
+mapfile -t words < <(shuf --random-source=/dev/urandom -r -n "$wordnum" < "$dict")
+
+if ! [[ ${#words[@]} = "$wordnum" ]]; then
+    echo "ERROR: could not read/shuffle the dictionary."
+    exit 1
+fi
 
 password=""
 for word in "${words[@]}"
@@ -29,18 +51,18 @@ fi
 if [ "$XDG_SESSION_TYPE" = "wayland" ]
 then
     if [ "$wlcopy_present" = true ]; then
-        clipcommand="xargs wl-copy"
+        clipcommand=(wl-copy)
     else
         echo "ERROR: please install wl-clipboard to use this script in a Wayland session."
         exit 42
     fi
 else
     if [ "$xclip_present" = true ]; then
-        clipcommand="xclip -i -sel clip"
+        clipcommand=(xclip -i -sel clip)
     else
         echo "ERROR: please install xclip to use this script in an X11 session."
         exit 42
     fi
 fi
 
-eval "echo '$password' | $clipcommand"
+printf '%s' "$password" | "${clipcommand[@]}"
