tstamp now correctly handles paths

diff --git a/tstamp b/tstamp
--- a/tstamp
+++ b/tstamp
@@ -9,28 +9,30 @@
 # % tstamp abc.txt    -> 2023-09-01_abc.txt
 # % tstamp abc.txt -t -> 2023-09-01T07-40_abc.txt
 
-fname="$1"
+fname=$(basename "$1")
+fdir=$(dirname "$1")
 
-if [ -z "$fname" ]; then
+if [ -z "$1" ]; then
 	echo "USAGE: tstamp <filename> [-t]"
 	exit 0
 fi
 
-if ! [ -f "$fname" ]; then
-	echo "ERROR: '${fname}' is not a file."
+if ! [ -f "$1" ]; then
+	echo "ERROR: '$1' is not a file."
 	exit 45
 fi
 
 timeopt="$2"
 
 if [ "x${timeopt}" = "x-t" ]; then
-	datetime="$(date -r "$fname" '+%Y-%m-%dT%H-%M')"
+	datetime="$(date -r "$1" '+%Y-%m-%dT%H-%M')"
 else
-	datetime="$(date -r "$fname" '+%Y-%m-%d' )"
+	datetime="$(date -r "$1" '+%Y-%m-%d' )"
 fi
 
 newfname="${datetime}_${fname}"
 
-echo "Renaming '${fname}' to '${newfname}'..."
+echo "Original name: '${fdir}/${fname}'."
+echo "Renaming to: '${fdir}/${newfname}'..."
 
-mv "$fname" "$newfname"
+mv "$fdir/$fname" "$fdir/$newfname"
